---
- name: Install postgresql-common
  ansible.builtin.apt:
    name: postgresql-common
    update_cache: true
    cache_valid_time: 3600
    state: present
  retries: 10
  delay: 10
  tags: [pgdg_repo]

- name: Add pgdg repo
  ansible.builtin.command:
    cmd: /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
    creates: /etc/apt/sources.list.d/pgdg.sources
  tags: [pgdg_repo]
...
